name = input("What is your name?: ")
age = int(input("What is your age?: "))
height = float(input("What is your height?: "))
print("Hello " + name + "!")
print("You are " + str(age) + " years old.")
print("You are " + str(height) + " cms tall.")
